# Generated by Django 4.2.6 on 2023-10-28 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdat",
                    models.DateField(auto_now=True, verbose_name="createdat"),
                ),
                (
                    "modifiedat",
                    models.DateField(auto_now=True, verbose_name="modifiedat"),
                ),
                (
                    "deletedat",
                    models.DateField(auto_now=True, verbose_name="deletedat"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                (
                    "customer_number",
                    models.CharField(max_length=50, verbose_name="رقم العميل"),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("1", "An individual"),
                            ("2", "a company"),
                            ("3", "Mail-man"),
                            ("4", "post-man"),
                        ],
                        max_length=50,
                        verbose_name="نوع العميل",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="الأسم")),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("employee", "Employee"),
                            ("teacher", "Teacher"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=100,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")], max_length=100
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="رقم التلفون",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        max_length=245, null=True, verbose_name="الأيميل"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الربط"
                    ),
                ),
                ("stop", models.BooleanField(default=False, verbose_name="موقف")),
                (
                    "reason",
                    models.CharField(max_length=200, null=True, verbose_name="السبب"),
                ),
                (
                    "identity_type",
                    models.CharField(
                        max_length=50, null=True, verbose_name="نوع الهوية"
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        max_length=50, null=True, verbose_name="رقم الهوية"
                    ),
                ),
                (
                    "issuer",
                    models.CharField(
                        max_length=50, null=True, verbose_name="جهة الأصدار"
                    ),
                ),
                (
                    "release_date",
                    models.DateField(null=True, verbose_name="تاريخ الأصدار"),
                ),
                (
                    "expiry_date",
                    models.DateField(null=True, verbose_name="تاريخ الأنتهاء"),
                ),
                ("join_date", models.DateField()),
                (
                    "deletedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_deletedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deletedby",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.department",
                    ),
                ),
                (
                    "modifiedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_modifiedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifiedby",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OWner",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.university",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_partner_linked",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": " بيانات العميل",
                "verbose_name_plural": " بيانات العملاء",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartnerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdat",
                    models.DateField(auto_now=True, verbose_name="createdat"),
                ),
                (
                    "modifiedat",
                    models.DateField(auto_now=True, verbose_name="modifiedat"),
                ),
                (
                    "deletedat",
                    models.DateField(auto_now=True, verbose_name="deletedat"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                (
                    "type_address",
                    models.CharField(max_length=50, verbose_name="type address"),
                ),
                (
                    "note",
                    models.CharField(max_length=50, null=True, verbose_name="Note"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.address",
                        verbose_name="Address",
                    ),
                ),
                (
                    "deletedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_deletedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deletedby",
                    ),
                ),
                (
                    "modifiedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_modifiedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifiedby",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OWner",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.partner",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
    ]
