# Generated by Django 4.2.6 on 2023-10-30 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='deletedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='deletedby'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الأنتهاء'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='identity_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الهوية'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='issuer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='جهة الأصدار'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='modifiedby'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='OWner'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='رقم التلفون'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='السبب'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الأصدار'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_partner_linked', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='user_email',
            field=models.EmailField(blank=True, max_length=245, null=True, verbose_name='الأيميل'),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='deletedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='deletedby'),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='modifiedby'),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='OWner'),
        ),
    ]
