# Generated by Django 4.2.6 on 2023-11-18 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_department_options_alter_university_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_alter_partner_deletedby_alter_partner_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='createdat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='هل حذف'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='deletedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='deletedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='حذفه '),
        ),
        migrations.AlterField(
            model_name='partner',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='modifiedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='عدله '),
        ),
        migrations.AlterField(
            model_name='partner',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='انشائه '),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=100, verbose_name='حالة العميل'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.university', verbose_name='الجامعة'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_partner_linked', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.address', verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='createdat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='هل حذف'),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='deletedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='deletedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='حذفه '),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='modifiedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='عدله '),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='انشائه '),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.partner', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='type_address',
            field=models.CharField(max_length=50, verbose_name='نوع العنوان'),
        ),
    ]
