# Generated by Django 4.2.7 on 2023-11-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_partner_createdat_alter_partner_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partneraddress',
            options={'verbose_name': ' عنوان العميل'},
        ),
    ]
