# Generated by Django 4.2.6 on 2023-11-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_partneraddress_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=100, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='user_type',
            field=models.CharField(choices=[('student', 'طالب'), ('employee', 'موظف'), ('teacher', 'مدرس')], max_length=100),
        ),
    ]
