# Generated by Django 4.2.6 on 2023-12-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_partner_gender_alter_partner_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم التلفون'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='user_type',
            field=models.CharField(choices=[('student', 'طالب'), ('employee', 'موظف'), ('teacher', 'مدرس')], max_length=100, verbose_name='نوع المستخدم'),
        ),
    ]
