# Generated by Django 4.2.6 on 2023-12-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_partner_phone_number_alter_partner_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partneraddress',
            name='address',
        ),
    ]
