# Generated by Django 4.2.6 on 2023-12-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_partneraddress_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='phone_number',
        ),
    ]
