# Generated by Django 4.2.6 on 2023-12-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_partner_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='user_email',
        ),
    ]
