# Generated by Django 4.2.6 on 2023-12-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_remove_partner_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='customer_number',
            field=models.IntegerField(verbose_name='رقم العميل'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='identification_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الهوية'),
        ),
    ]
