# Generated by Django 4.2.6 on 2023-12-05 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0011_remove_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الفترة')),
                ('period_type', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], max_length=20, verbose_name='نوع الفترة')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('active', 'فعال'), ('locked', 'مقفل'), ('stopped', 'موقف')], default='new', max_length=20, verbose_name='حالة')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.university', verbose_name='الجامعة')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField(verbose_name='رقم الفترة')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الفترة')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('active', 'فعال'), ('locked', 'مقفل'), ('stopped', 'موقف')], default='new', max_length=20, verbose_name='حالة')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periods.period', verbose_name='الفترة')),
            ],
        ),
    ]
