# Generated by Django 4.2.6 on 2023-12-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'الرئيسي', 'verbose_name_plural': 'التفصيلي'},
        ),
        migrations.AlterModelOptions(
            name='perioddetail',
            options={'verbose_name': 'التفصيلي', 'verbose_name_plural': 'التفصيلي'},
        ),
    ]
