# Generated by Django 4.2.6 on 2023-12-10 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0002_alter_period_options_alter_perioddetail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'الرئيسي', 'verbose_name_plural': 'الرئيسي'},
        ),
    ]
