# Generated by Django 4.2.6 on 2023-11-18 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_department_options_alter_university_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowing', '0002_alter_assetsissuance_asset_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsissuance',
            name='createdat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='assetsissuance',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='هل حذف'),
        ),
        migrations.AlterField(
            model_name='assetsissuance',
            name='deletedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AlterField(
            model_name='assetsissuance',
            name='deletedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='حذفه '),
        ),
        migrations.AlterField(
            model_name='assetsissuance',
            name='modifiedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='assetsissuance',
            name='modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='عدله '),
        ),
        migrations.AlterField(
            model_name='assetsissuance',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='انشائه '),
        ),
        migrations.AlterField(
            model_name='assetsissuance',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to='base.university', verbose_name='الجامعة'),
        ),
    ]
