# Generated by Django 4.2.6 on 2023-10-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(blank=False, max_length=100)),
                ("name", models.CharField(max_length=100, null=True)),
                ("quantity", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Used", "Used"),
                            ("Replacement", "Replacement"),
                        ],
                        max_length=100,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("activation_date", models.DateField()),
                ("usage_period", models.CharField(max_length=100)),
                ("creation_date", models.DateField()),
                ("asset_admin", models.CharField(max_length=100, null=True)),
                ("maintenance_required", models.BooleanField()),
                ("borrow_able", models.BooleanField()),
                ("asset_issued", models.BooleanField(default=False)),
                (
                    "asset_image",
                    models.ImageField(default="default.jpeg", upload_to="images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdat",
                    models.DateField(auto_now=True, verbose_name="createdat"),
                ),
                (
                    "modifiedat",
                    models.DateField(auto_now=True, verbose_name="modifiedat"),
                ),
                (
                    "deletedat",
                    models.DateField(auto_now=True, verbose_name="deletedat"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("name", models.CharField(blank=False, max_length=100)),
                ("description", models.CharField(blank=False, max_length=100)),
                ("category_admin", models.CharField(blank=False, max_length=100)),
                ("is_group", models.BooleanField(default=False, verbose_name="مجموعة")),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdat",
                    models.DateField(auto_now=True, verbose_name="createdat"),
                ),
                (
                    "modifiedat",
                    models.DateField(auto_now=True, verbose_name="modifiedat"),
                ),
                (
                    "deletedat",
                    models.DateField(auto_now=True, verbose_name="deletedat"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("name", models.CharField(blank=False, max_length=100)),
                ("description", models.CharField(blank=False, max_length=100)),
                ("is_group", models.BooleanField(default=False, verbose_name="مجموعة")),
                ("area", models.CharField(max_length=255)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
    ]
