# Generated by Django 4.2.6 on 2023-10-28 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0001_initial"),
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="deletedby",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_deletedby_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="deletedby",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="modifiedby",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_modifiedby_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="modifiedby",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_ownership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="OWner",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="assets.location",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="university",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.university",
            ),
        ),
        migrations.AddField(
            model_name="assetcategory",
            name="deletedby",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_deletedby_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="deletedby",
            ),
        ),
        migrations.AddField(
            model_name="assetcategory",
            name="modifiedby",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_modifiedby_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="modifiedby",
            ),
        ),
        migrations.AddField(
            model_name="assetcategory",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_ownership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="OWner",
            ),
        ),
        migrations.AddField(
            model_name="assetcategory",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="assets.assetcategory",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assets.assetcategory"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.department"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assets.location"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.university"
            ),
        ),
    ]
