# Generated by Django 4.2.6 on 2023-11-13 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_address_address_line_alter_address_city_and_more'),
        ('assets', '0008_alter_asset_activation_date_alter_asset_asset_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الباركود'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.assetcategory'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.department'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.university'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='usage_period',
            field=models.DateField(verbose_name='فترة الأستخدام'),
        ),
        migrations.AlterField(
            model_name='location',
            name='area',
            field=models.CharField(max_length=255, verbose_name='المساحة '),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=100, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
    ]
