# Generated by Django 4.2.6 on 2023-11-18 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_department_options_alter_university_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0009_alter_asset_barcode_alter_asset_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'الأصول', 'verbose_name_plural': 'الأصول'},
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'verbose_name': 'فئات الأصول', 'verbose_name_plural': 'فئات الأصول'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'المواقع', 'verbose_name_plural': 'المواقع'},
        ),
        migrations.AlterModelManagers(
            name='assetcategory',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.assetcategory', verbose_name='الفئه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.location', verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.university', verbose_name='الجامعة'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='createdat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الأنشاء'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='هل محذوف'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='deletedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='deletedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='عدله'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='modifiedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='حذف'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='انشائه'),
        ),
        migrations.AlterField(
            model_name='location',
            name='createdat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الأنشاء'),
        ),
        migrations.AlterField(
            model_name='location',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='هل محذوف'),
        ),
        migrations.AlterField(
            model_name='location',
            name='deletedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AlterField(
            model_name='location',
            name='deletedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='عدله'),
        ),
        migrations.AlterField(
            model_name='location',
            name='modifiedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='location',
            name='modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='حذف'),
        ),
        migrations.AlterField(
            model_name='location',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='انشائه'),
        ),
        migrations.AlterField(
            model_name='location',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.university', verbose_name='الجامعة'),
        ),
    ]
