# Generated by Django 4.2.7 on 2023-11-27 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_department_options_alter_university_options_and_more'),
        ('customer', '0004_alter_partneraddress_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0010_alter_asset_options_alter_assetcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateField(auto_now=True, verbose_name='تاريخ الانشاء')),
                ('modifiedat', models.DateField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deletedat', models.DateField(auto_now=True, verbose_name='تاريخ الحذف')),
                ('deleted', models.BooleanField(default=False, verbose_name='هل حذف')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('in', 'in'), ('out', 'out'), ('non', 'in')], max_length=100)),
                ('type_movement', models.CharField(choices=[('in', 'in'), ('out', 'out'), ('non', 'in')], max_length=100)),
                ('purpose', models.CharField(max_length=100, verbose_name='الغرض')),
                ('transaction_date', models.DateField(verbose_name='تاريخ الحركة')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('deletedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='حذفه ')),
                ('from_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_from_company_mov', to='base.university')),
                ('from_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_lines_as_from_employee_mov', to='customer.partner')),
                ('modifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='عدله ')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='انشائه ')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_source_mov', to='assets.location')),
                ('target_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_target_mov', to='assets.location')),
                ('to_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_to_company_mov', to='base.university')),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_lines_as_to_employee_mov', to='customer.partner')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
    ]
