# Generated by Django 4.2.6 on 2023-11-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_movementassets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movementassets',
            old_name='from_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='movementassets',
            old_name='from_employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='movementassets',
            old_name='source_location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='movementassets',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='movementassets',
            name='target_location',
        ),
        migrations.RemoveField(
            model_name='movementassets',
            name='to_company',
        ),
        migrations.RemoveField(
            model_name='movementassets',
            name='to_employee',
        ),
        migrations.RemoveField(
            model_name='movementassets',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='movementassets',
            name='type_movement',
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('1', 'جديد'), ('2', 'استعارة'), ('3', 'استعادة'), ('4', 'تلف'), ('4', 'خسارة'), ('5', 'اهداء'), ('6', 'بيع'), ('7', 'صيانة'), ('8', 'نقل')], default=1, max_length=100, verbose_name='نوع الموقع'),
            preserve_default=False,
        ),
    ]
