# Generated by Django 4.2.6 on 2023-11-29 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_partner_gender_alter_partner_user_type'),
        ('base', '0005_alter_university_establishment_date_and_more'),
        ('assets', '0012_rename_from_company_movementassets_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movementassets',
            options={'verbose_name': 'حركة الأصل', 'verbose_name_plural': 'حركة الأصل'},
        ),
        migrations.AlterField(
            model_name='movementassets',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='الأصل'),
        ),
        migrations.AlterField(
            model_name='movementassets',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_from_company_mov', to='base.university', verbose_name='الجامعة'),
        ),
        migrations.AlterField(
            model_name='movementassets',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_lines_as_from_employee_mov', to='customer.partner', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='movementassets',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_source_mov', to='assets.location', verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='movementassets',
            name='quantity',
            field=models.IntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='movementassets',
            name='status',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out'), ('non', 'in')], max_length=100, verbose_name='الحالة'),
        ),
    ]
