# Generated by Django 4.2.6 on 2023-11-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_alter_movementassets_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('1', 'جديد'), ('2', 'استعارة'), ('3', 'استعادة'), ('4', 'تلف'), ('4', 'خسارة'), ('5', 'اهداء'), ('6', 'بيع'), ('7', 'صيانة'), ('8', 'نقل')], help_text='هذا يكون أختيار نوع الموقع ', max_length=100, verbose_name='نوع الموقع'),
        ),
    ]
