# Generated by Django 4.2.6 on 2023-11-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_partner_gender_alter_partner_user_type'),
        ('assets', '0014_alter_location_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.partner', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('1', 'داخلي'), ('2', 'عملاء'), ('3', 'نقل'), ('4', 'تالف \\خساره'), ('5', 'موردين'), ('6', 'صيانه'), ('7', 'الافتتاحي')], help_text='هذا يكون أختيار نوع الموقع ', max_length=100, verbose_name='نوع الموقع'),
        ),
    ]
