# Generated by Django 4.2.6 on 2023-12-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_asset_employee_alter_location_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='activation_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التفعيل'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاضافة'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='usage_period',
            field=models.DateField(blank=True, null=True, verbose_name='فترة الأستخدام'),
        ),
    ]
