# Generated by Django 4.2.6 on 2023-12-10 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_alter_movementassets_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='barcode',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='الباركود'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetcategory', verbose_name='نوع الأصل'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('1', 'فعال'), ('2', 'غير فعال'), ('3', 'موقف'), ('4', 'مستبعد')], max_length=100, verbose_name='الحالة'),
        ),
    ]
