# Generated by Django 4.2.7 on 2023-12-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_alter_asset_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementassets',
            name='count_quantity',
            field=models.IntegerField(default=1, verbose_name='الكمية المحسوبة'),
            preserve_default=False,
        ),
    ]
