# Generated by Django 4.2.6 on 2023-10-28 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdat",
                    models.DateField(auto_now=True, verbose_name="createdat"),
                ),
                (
                    "modifiedat",
                    models.DateField(auto_now=True, verbose_name="modifiedat"),
                ),
                (
                    "deletedat",
                    models.DateField(auto_now=True, verbose_name="deletedat"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("name", models.CharField(max_length=100)),
                ("contact_person", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.TextField()),
                (
                    "deletedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_deletedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deletedby",
                    ),
                ),
                (
                    "modifiedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_modifiedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifiedby",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OWner",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="AssetReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdat",
                    models.DateField(auto_now=True, verbose_name="createdat"),
                ),
                (
                    "modifiedat",
                    models.DateField(auto_now=True, verbose_name="modifiedat"),
                ),
                (
                    "deletedat",
                    models.DateField(auto_now=True, verbose_name="deletedat"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("receipt_number", models.CharField(max_length=100)),
                ("asset_name", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("receipt_date", models.DateField()),
                (
                    "deletedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_deletedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deletedby",
                    ),
                ),
                (
                    "modifiedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_modifiedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifiedby",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OWner",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchase.supplier",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to="base.university",
                        verbose_name="الشركة",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="AssetPurchaseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdat",
                    models.DateField(auto_now=True, verbose_name="createdat"),
                ),
                (
                    "modifiedat",
                    models.DateField(auto_now=True, verbose_name="modifiedat"),
                ),
                (
                    "deletedat",
                    models.DateField(auto_now=True, verbose_name="deletedat"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("asset_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "deletedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_deletedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deletedby",
                    ),
                ),
                (
                    "modifiedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_modifiedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifiedby",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OWner",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to="base.university",
                        verbose_name="الشركة",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="AssetInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdat",
                    models.DateField(auto_now=True, verbose_name="createdat"),
                ),
                (
                    "modifiedat",
                    models.DateField(auto_now=True, verbose_name="modifiedat"),
                ),
                (
                    "deletedat",
                    models.DateField(auto_now=True, verbose_name="deletedat"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("invoice_number", models.CharField(max_length=100)),
                ("asset_name", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("invoice_date", models.DateField()),
                (
                    "deletedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_deletedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deletedby",
                    ),
                ),
                (
                    "modifiedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_modifiedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifiedby",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OWner",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchase.supplier",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to="base.university",
                        verbose_name="الشركة",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
    ]
