# Generated by Django 4.2.7 on 2023-11-27 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0003_alter_assetinvoice_createdat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetinvoice',
            options={'verbose_name': '   فاتورةشراء الأصول', 'verbose_name_plural': ' فاتورة شراء الأصول '},
        ),
        migrations.AlterModelOptions(
            name='assetpurchaserequest',
            options={'verbose_name': ' طلب شراء الأصول', 'verbose_name_plural': ' طلب شراء الأصول'},
        ),
        migrations.AlterModelOptions(
            name='assetreceipt',
            options={'verbose_name': '    استلام الأصول', 'verbose_name_plural': '  استلام الأصول  '},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': ' المورد', 'verbose_name_plural': ' المورد'},
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='asset_name',
            field=models.CharField(max_length=100, verbose_name=' اسم الأصل'),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='invoice_date',
            field=models.DateField(verbose_name=' تاريخ الفاتورة'),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='invoice_number',
            field=models.CharField(max_length=100, verbose_name=' رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name=' الكمية'),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.supplier', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name=' السعر الإجمالي'),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name=' سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='assetpurchaserequest',
            name='asset_name',
            field=models.CharField(max_length=100, verbose_name='اسم الأصل'),
        ),
        migrations.AlterField(
            model_name='assetpurchaserequest',
            name='date',
            field=models.DateTimeField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='assetpurchaserequest',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='assetpurchaserequest',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='assetpurchaserequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المطلب'),
        ),
        migrations.AlterField(
            model_name='assetpurchaserequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='assetpurchaserequest',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الإجمالي'),
        ),
        migrations.AlterField(
            model_name='assetpurchaserequest',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='assetreceipt',
            name='asset_name',
            field=models.CharField(max_length=100, verbose_name=' اسم الأصل'),
        ),
        migrations.AlterField(
            model_name='assetreceipt',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name=' الكمية'),
        ),
        migrations.AlterField(
            model_name='assetreceipt',
            name='receipt_date',
            field=models.DateField(verbose_name='  تاريخ الاستلام'),
        ),
        migrations.AlterField(
            model_name='assetreceipt',
            name='receipt_number',
            field=models.CharField(max_length=100, verbose_name=' رقم الاستلام'),
        ),
        migrations.AlterField(
            model_name='assetreceipt',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.supplier', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='assetreceipt',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name=' السعر الإجمالي'),
        ),
        migrations.AlterField(
            model_name='assetreceipt',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name=' سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(max_length=100, verbose_name='الشخص المتصل به'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='الإيميل'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
    ]
