# Generated by Django 4.2.6 on 2023-11-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_assetinvoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetpurchaserequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد الانتظار'), ('Approved', 'موافق عليه'), ('Rejected', 'مرفوض')], default='Pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
