# Generated by Django 4.2.6 on 2023-11-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_alter_assetpurchaserequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetreceipt',
            options={'verbose_name': 'استلام الأصول', 'verbose_name_plural': 'استلام'},
        ),
    ]
