# Generated by Django 4.2.6 on 2023-10-30 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_address_address_line_alter_address_city_and_more'),
        ('customer', '0002_alter_partner_deletedby_alter_partner_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='deletedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='deletedby'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='modifiedby'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='OWner'),
        ),
        migrations.AlterField(
            model_name='movementline',
            name='deletedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='deletedby'),
        ),
        migrations.AlterField(
            model_name='movementline',
            name='from_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_from_company', to='base.university'),
        ),
        migrations.AlterField(
            model_name='movementline',
            name='from_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_lines_as_from_employee', to='customer.partner'),
        ),
        migrations.AlterField(
            model_name='movementline',
            name='modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='modifiedby'),
        ),
        migrations.AlterField(
            model_name='movementline',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='OWner'),
        ),
        migrations.AlterField(
            model_name='movementline',
            name='to_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_to_company', to='base.university'),
        ),
        migrations.AlterField(
            model_name='movementline',
            name='to_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_lines_as_to_employee', to='customer.partner'),
        ),
    ]
