# Generated by Django 4.2.7 on 2023-11-27 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_movementassets'),
        ('base', '0004_alter_department_options_alter_university_options_and_more'),
        ('customer', '0004_alter_partneraddress_options'),
        ('movement', '0003_alter_movement_createdat_alter_movement_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movement',
            options={'verbose_name': ' الحركة', 'verbose_name_plural': ' الحركة'},
        ),
        migrations.AddField(
            model_name='movement',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='الأصل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movement',
            name='from_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_from_company', to='base.university', verbose_name='من الجامعة'),
        ),
        migrations.AddField(
            model_name='movement',
            name='from_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_lines_as_from_employee', to='customer.partner', verbose_name='من الموظف'),
        ),
        migrations.AddField(
            model_name='movement',
            name='source_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_source', to='assets.location', verbose_name='موقع المصدر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movement',
            name='target_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_target', to='assets.location', verbose_name='موقع الهدف '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movement',
            name='to_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_to_company', to='base.university', verbose_name='إلى الجامعة'),
        ),
        migrations.AddField(
            model_name='movement',
            name='to_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_lines_as_to_employee', to='customer.partner', verbose_name='إلى الموظف'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='purpose',
            field=models.CharField(max_length=100, verbose_name='الغرض'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='reference_doctype',
            field=models.CharField(max_length=100, verbose_name='نوع الحركة'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='reference_name',
            field=models.CharField(max_length=100, verbose_name='اسم الحركة'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='transaction_date',
            field=models.DateField(verbose_name='تاريخ الحركة'),
        ),
        migrations.DeleteModel(
            name='MovementLine',
        ),
    ]
