# Generated by Django 4.2.6 on 2023-11-28 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0012_rename_from_company_movementassets_company_and_more'),
        ('movement', '0005_movement_quantity_movement_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateField(auto_now=True, verbose_name='تاريخ الانشاء')),
                ('modifiedat', models.DateField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deletedat', models.DateField(auto_now=True, verbose_name='تاريخ الحذف')),
                ('deleted', models.BooleanField(default=False, verbose_name='هل حذف')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('deletedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='حذفه ')),
                ('modifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='عدله ')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='انشائه ')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_sourcedef', to='assets.location', verbose_name='موقع المصدر')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_targetdef', to='assets.location', verbose_name='موقع الهدف ')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.AlterField(
            model_name='movement',
            name='type_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_to_company', to='movement.movementtype', verbose_name=' type_movement'),
        ),
    ]
