# Generated by Django 4.2.6 on 2023-11-29 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0006_movementtype_alter_movement_type_movement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movementtype',
            options={'verbose_name': ' نوع الحركة', 'verbose_name_plural': ' نوع الحركة'},
        ),
        migrations.AlterField(
            model_name='movement',
            name='status',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out'), ('non', 'in')], max_length=100, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='type_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_to_company', to='movement.movementtype', verbose_name=' نوع الحركة'),
        ),
        migrations.AlterField(
            model_name='movementtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='movementtype',
            name='type',
            field=models.CharField(max_length=100, verbose_name='النوع'),
        ),
    ]
