# Generated by Django 4.2.6 on 2023-11-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0007_alter_movementtype_options_alter_movement_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='reference_doctype',
        ),
    ]
