# Generated by Django 4.2.6 on 2023-11-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0008_remove_movement_reference_doctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.IntegerField(verbose_name='الكمية'),
        ),
    ]
