# Generated by Django 4.2.6 on 2023-12-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0009_alter_movement_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='transaction_date',
        ),
        migrations.AlterField(
            model_name='movementtype',
            name='type',
            field=models.CharField(choices=[('1', 'أضافة'), ('2', 'أستعارة'), ('3', 'نقل'), ('4', 'صيانة'), ('5', 'شراء '), ('6', 'بيع')], max_length=100, verbose_name='نوع الحركة'),
        ),
    ]
