# Generated by Django 4.2.6 on 2023-12-02 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_remove_partner_user_email'),
        ('movement', '0010_remove_movement_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='from_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_lines_as_from_employee', to='customer.partner', verbose_name='من العميل'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='to_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_lines_as_to_employee', to='customer.partner', verbose_name='إلى العميل'),
        ),
    ]
