# Generated by Django 4.2.6 on 2023-12-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0011_alter_movement_from_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='transaction_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الحركة'),
        ),
    ]
