# Generated by Django 4.2.6 on 2023-12-06 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('periods', '0002_alter_period_options_alter_perioddetail_options'),
        ('assets', '0017_alter_movementassets_employee'),
        ('movement', '0012_movement_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stodetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateField(auto_now=True, verbose_name='تاريخ الانشاء')),
                ('modifiedat', models.DateField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deletedat', models.DateField(auto_now=True, verbose_name='تاريخ الحذف')),
                ('deleted', models.BooleanField(default=False, verbose_name='هل حذف')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('مفقود', 'مفقود'), ('موجود', 'موجود'), ('منقول', 'منقول')], max_length=100, verbose_name='الحالة')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='الأصل')),
                ('deletedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='حذفه ')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.location', verbose_name='الموقع')),
                ('modifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='عدله ')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='انشائه ')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periods.period', verbose_name='الفترة')),
            ],
            options={
                'verbose_name': 'تفاصيل المخزون',
                'verbose_name_plural': 'تفاصيل المخزون',
            },
        ),
    ]
