# Generated by Django 4.2.6 on 2023-12-06 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_alter_movementassets_employee'),
        ('base', '0011_remove_user_phone'),
        ('movement', '0014_rename_stodetails_stockdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetails',
            name='new_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stockdetails_new_location', to='assets.location', verbose_name='الموقع الجديد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movement',
            name='from_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_from_company', to='base.university', verbose_name=' الجامعة المرسله'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='to_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines_as_to_company', to='base.university', verbose_name='  الجامعة المستلمة'),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockdetails_location', to='assets.location', verbose_name='الموقع'),
        ),
    ]
