# Generated by Django 4.2.6 on 2023-12-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0015_stockdetails_new_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetails',
            name='actual_quantity',
            field=models.IntegerField(default=1, verbose_name='الكمية الفعلية'),
            preserve_default=False,
        ),
    ]
