# Generated by Django 4.2.6 on 2023-12-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0016_stockdetails_actual_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdetails',
            options={'verbose_name': 'تفاصيل الجرد', 'verbose_name_plural': 'تفاصيل الجرد'},
        ),
        migrations.RemoveField(
            model_name='stockdetails',
            name='date',
        ),
        migrations.AddField(
            model_name='stockdetails',
            name='barcode',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='رقم الباركود'),
        ),
        migrations.AddField(
            model_name='stockdetails',
            name='recipient',
            field=models.CharField(default=1, max_length=100, verbose_name='المستلم الجديد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='actual_quantity',
            field=models.IntegerField(verbose_name='كمية الجرد (الفعلية)'),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='status',
            field=models.CharField(choices=[('مفقود', 'مفقود'), ('موجود', 'موجود'), ('منقول', 'منقول')], max_length=100, verbose_name='حالة الجرد'),
        ),
    ]
