# Generated by Django 4.2.6 on 2023-12-10 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0003_alter_period_options'),
        ('base', '0011_remove_user_phone'),
        ('movement', '0018_alter_stockdetails_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdetails',
            name='period',
        ),
        migrations.CreateModel(
            name='maindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('lnventory_methods', models.CharField(choices=[('1', 'إنزال آلي للأصول'), ('2', 'إدخال يدوي للأصول'), ('3', 'جرد الأصول غير المجرودة')], max_length=100, verbose_name='طريقة الجرد')),
                ('University', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.university', verbose_name=' الجامعة ')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periods.period', verbose_name='الفترة')),
            ],
            options={
                'verbose_name': ' البيانات الرئيسية',
                'verbose_name_plural': ' جرد الأصول',
            },
        ),
    ]
