# Generated by Django 4.2.6 on 2023-12-11 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0020_stockdetails_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetails',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movement.maindata', verbose_name='الفترة'),
        ),
    ]
