# Generated by Django 4.2.6 on 2023-12-11 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0021_alter_stockdetails_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdetails',
            name='period',
        ),
        migrations.AddField(
            model_name='stockdetails',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movement.maindata', verbose_name='السنة'),
            preserve_default=False,
        ),
    ]
