# Generated by Django 4.2.7 on 2023-12-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0022_remove_stockdetails_period_stockdetails_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdetails',
            options={'verbose_name': ' البيانات التفصيلية', 'verbose_name_plural': 'البيانات التفصيلية  '},
        ),
    ]
