# Generated by Django 4.2.6 on 2023-10-28 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0001_initial"),
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetRepair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdat",
                    models.DateField(auto_now=True, verbose_name="createdat"),
                ),
                (
                    "modifiedat",
                    models.DateField(auto_now=True, verbose_name="modifiedat"),
                ),
                (
                    "deletedat",
                    models.DateField(auto_now=True, verbose_name="deletedat"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("naming_series", models.CharField(max_length=100)),
                ("failure_date", models.DateField()),
                ("completion_date", models.DateField(null=True)),
                (
                    "repair_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("actions_performed", models.TextField()),
                ("downtime", models.DecimalField(decimal_places=2, max_digits=10)),
                ("repair_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("asset_name", models.CharField(max_length=100)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.asset"
                    ),
                ),
                (
                    "deletedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_deletedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deletedby",
                    ),
                ),
                (
                    "modifiedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_modifiedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifiedby",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OWner",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to="base.university",
                        verbose_name="الشركة",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdat",
                    models.DateField(auto_now=True, verbose_name="createdat"),
                ),
                (
                    "modifiedat",
                    models.DateField(auto_now=True, verbose_name="modifiedat"),
                ),
                (
                    "deletedat",
                    models.DateField(auto_now=True, verbose_name="deletedat"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("priority", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_deletedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deletedby",
                    ),
                ),
                (
                    "modifiedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_modifiedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifiedby",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OWner",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdat",
                    models.DateField(auto_now=True, verbose_name="createdat"),
                ),
                (
                    "modifiedat",
                    models.DateField(auto_now=True, verbose_name="modifiedat"),
                ),
                (
                    "deletedat",
                    models.DateField(auto_now=True, verbose_name="deletedat"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("team_name", models.CharField(max_length=100)),
                (
                    "deletedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_deletedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deletedby",
                    ),
                ),
                (
                    "modifiedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_modifiedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifiedby",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OWner",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to="base.university",
                        verbose_name="الشركة",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdat",
                    models.DateField(auto_now=True, verbose_name="createdat"),
                ),
                (
                    "modifiedat",
                    models.DateField(auto_now=True, verbose_name="modifiedat"),
                ),
                (
                    "deletedat",
                    models.DateField(auto_now=True, verbose_name="deletedat"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                (
                    "deletedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_deletedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deletedby",
                    ),
                ),
                (
                    "maintenance_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.maintenanceteam",
                    ),
                ),
                (
                    "modifiedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_modifiedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifiedby",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OWner",
                    ),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdat",
                    models.DateField(auto_now=True, verbose_name="createdat"),
                ),
                (
                    "modifiedat",
                    models.DateField(auto_now=True, verbose_name="modifiedat"),
                ),
                (
                    "deletedat",
                    models.DateField(auto_now=True, verbose_name="deletedat"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.asset"
                    ),
                ),
                (
                    "deletedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_deletedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deletedby",
                    ),
                ),
                (
                    "maintenance_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "maintenance_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.maintenanceteam",
                    ),
                ),
                (
                    "modifiedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_modifiedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifiedby",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OWner",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to="base.university",
                        verbose_name="الشركة",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="AssetRepairConsumedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdat",
                    models.DateField(auto_now=True, verbose_name="createdat"),
                ),
                (
                    "modifiedat",
                    models.DateField(auto_now=True, verbose_name="modifiedat"),
                ),
                (
                    "deletedat",
                    models.DateField(auto_now=True, verbose_name="deletedat"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                (
                    "valuation_rate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "consumed_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("serial_no", models.CharField(max_length=100)),
                ("item_code", models.CharField(max_length=100)),
                (
                    "asset_repair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.assetrepair",
                    ),
                ),
                (
                    "deletedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_deletedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deletedby",
                    ),
                ),
                (
                    "modifiedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_modifiedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifiedby",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OWner",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="AssetMaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdat",
                    models.DateField(auto_now=True, verbose_name="createdat"),
                ),
                (
                    "modifiedat",
                    models.DateField(auto_now=True, verbose_name="modifiedat"),
                ),
                (
                    "deletedat",
                    models.DateField(auto_now=True, verbose_name="deletedat"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("naming_series", models.CharField(max_length=100)),
                ("asset_name", models.CharField(max_length=100)),
                ("item_code", models.CharField(max_length=100)),
                ("item_name", models.CharField(max_length=100)),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("Preventive", "Preventive"),
                            ("Corrective", "Corrective"),
                            ("Predictive", "Predictive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("periodicity", models.CharField(max_length=100)),
                ("assign_to_name", models.CharField(max_length=100)),
                ("due_date", models.DateField()),
                ("completion_date", models.DateField(null=True)),
                (
                    "maintenance_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("has_certificate", models.BooleanField(default=False)),
                (
                    "certificate_attachment",
                    models.FileField(null=True, upload_to="certificates/"),
                ),
                ("description", models.TextField()),
                ("actions_performed", models.TextField()),
                ("task_name", models.CharField(max_length=100)),
                (
                    "amended_from",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="maintenance.assetmaintenancelog",
                    ),
                ),
                (
                    "asset_maintenance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.maintenanceasset",
                    ),
                ),
                (
                    "deletedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_deletedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deletedby",
                    ),
                ),
                (
                    "modifiedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_modifiedby_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifiedby",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OWner",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.task",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
    ]
