# Generated by Django 4.2.6 on 2023-11-18 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_asset_options_alter_assetcategory_options_and_more'),
        ('base', '0004_alter_department_options_alter_university_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0002_alter_assetmaintenancelog_amended_from_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceasset',
            options={'verbose_name': 'صيانة الأصول', 'verbose_name_plural': 'صيانة الأصول'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceteam',
            options={'verbose_name': 'فريق الصيانة', 'verbose_name_plural': 'فريق الصيانة'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'المهام', 'verbose_name_plural': 'المهام'},
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='createdat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='هل حذف'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='deletedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='deletedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='حذفه '),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='modifiedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='عدله '),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='انشائه '),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='createdat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='هل حذف'),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='deletedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='deletedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='حذفه '),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='modifiedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='عدله '),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='انشائه '),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to='base.university', verbose_name='الجامعة'),
        ),
        migrations.AlterField(
            model_name='assetrepairconsumeditem',
            name='createdat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='assetrepairconsumeditem',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='هل حذف'),
        ),
        migrations.AlterField(
            model_name='assetrepairconsumeditem',
            name='deletedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AlterField(
            model_name='assetrepairconsumeditem',
            name='deletedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='حذفه '),
        ),
        migrations.AlterField(
            model_name='assetrepairconsumeditem',
            name='modifiedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='assetrepairconsumeditem',
            name='modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='عدله '),
        ),
        migrations.AlterField(
            model_name='assetrepairconsumeditem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='انشائه '),
        ),
        migrations.AlterField(
            model_name='maintenanceasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='الأصل'),
        ),
        migrations.AlterField(
            model_name='maintenanceasset',
            name='createdat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='maintenanceasset',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='هل حذف'),
        ),
        migrations.AlterField(
            model_name='maintenanceasset',
            name='deletedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AlterField(
            model_name='maintenanceasset',
            name='deletedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='حذفه '),
        ),
        migrations.AlterField(
            model_name='maintenanceasset',
            name='maintenance_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدير الصيانة'),
        ),
        migrations.AlterField(
            model_name='maintenanceasset',
            name='maintenance_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenanceteam', verbose_name='فريق الصيانة'),
        ),
        migrations.AlterField(
            model_name='maintenanceasset',
            name='modifiedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='maintenanceasset',
            name='modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='عدله '),
        ),
        migrations.AlterField(
            model_name='maintenanceasset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='انشائه '),
        ),
        migrations.AlterField(
            model_name='maintenanceasset',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to='base.university', verbose_name='الجامعة'),
        ),
        migrations.AlterField(
            model_name='maintenancemember',
            name='createdat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='maintenancemember',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='هل حذف'),
        ),
        migrations.AlterField(
            model_name='maintenancemember',
            name='deletedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AlterField(
            model_name='maintenancemember',
            name='deletedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='حذفه '),
        ),
        migrations.AlterField(
            model_name='maintenancemember',
            name='modifiedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='maintenancemember',
            name='modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='عدله '),
        ),
        migrations.AlterField(
            model_name='maintenancemember',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='انشائه '),
        ),
        migrations.AlterField(
            model_name='maintenanceteam',
            name='createdat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='maintenanceteam',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='هل حذف'),
        ),
        migrations.AlterField(
            model_name='maintenanceteam',
            name='deletedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AlterField(
            model_name='maintenanceteam',
            name='deletedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='حذفه '),
        ),
        migrations.AlterField(
            model_name='maintenanceteam',
            name='modifiedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='maintenanceteam',
            name='modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='عدله '),
        ),
        migrations.AlterField(
            model_name='maintenanceteam',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='انشائه '),
        ),
        migrations.AlterField(
            model_name='maintenanceteam',
            name='team_name',
            field=models.CharField(max_length=100, verbose_name='اسم الفريق'),
        ),
        migrations.AlterField(
            model_name='maintenanceteam',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to='base.university', verbose_name='الجامعة'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تعيين لـ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='createdat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='هل حذف'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deletedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deletedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deletedby_set', to=settings.AUTH_USER_MODEL, verbose_name='حذفه '),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='task',
            name='modifiedat',
            field=models.DateField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='task',
            name='modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modifiedby_set', to=settings.AUTH_USER_MODEL, verbose_name='عدله '),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL, verbose_name='انشائه '),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(verbose_name='الأولويه '),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='الحالة '),
        ),
    ]
