# Generated by Django 4.2.7 on 2023-11-27 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_movementassets'),
        ('maintenance', '0003_alter_maintenanceasset_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetmaintenancelog',
            options={'verbose_name': 'سجل الصيانة', 'verbose_name_plural': 'سجل الصيانة'},
        ),
        migrations.AlterModelOptions(
            name='assetrepair',
            options={'verbose_name': ' إصلاح الأصول', 'verbose_name_plural': ' إصلاح الأصول'},
        ),
        migrations.AlterModelOptions(
            name='assetrepairconsumeditem',
            options={'verbose_name': 'إستهلاك الأصول', 'verbose_name_plural': 'إستهلاك الأصول'},
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='actions_performed',
            field=models.TextField(verbose_name='الإجراءت المنفذه'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='amended_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.assetmaintenancelog', verbose_name='تم التعديل'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='asset_maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenanceasset', verbose_name='أصل'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='asset_name',
            field=models.CharField(max_length=100, verbose_name='اسم الأصل'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='assign_to_name',
            field=models.CharField(max_length=100, verbose_name='تعيين'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='certificate_attachment',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='شهادة'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الأنتهاء'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='due_date',
            field=models.DateField(verbose_name='تاريخ'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='has_certificate',
            field=models.BooleanField(default=False, verbose_name='لديه شهادة'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='item_code',
            field=models.CharField(max_length=100, verbose_name='الغرض'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='اسم العصر'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='maintenance_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='حالةالصيانة'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='maintenance_type',
            field=models.CharField(choices=[('Preventive', 'Preventive'), ('Corrective', 'Corrective'), ('Predictive', 'Predictive')], max_length=20, verbose_name='نوع الصيانة'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='naming_series',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='periodicity',
            field=models.CharField(max_length=100, verbose_name='دوريه'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.task', verbose_name='المهمه'),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='task_name',
            field=models.CharField(max_length=100, verbose_name='اسم المهمه'),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='actions_performed',
            field=models.TextField(verbose_name='الإجراءات المنفذه'),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='أصل'),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='asset_name',
            field=models.CharField(max_length=100, verbose_name='اسم الأصل'),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ أنتهاء الإصلاح'),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='downtime',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار الوقت'),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='failure_date',
            field=models.DateField(verbose_name='تاريخ الإعطال'),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='repair_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الإصلاح'),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='repair_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='حالة الإصلاح'),
        ),
        migrations.AlterField(
            model_name='assetrepairconsumeditem',
            name='asset_repair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.assetrepair', verbose_name='الأصل المستهلك'),
        ),
        migrations.AlterField(
            model_name='assetrepairconsumeditem',
            name='consumed_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='كمية العنصر المستهلك '),
        ),
        migrations.AlterField(
            model_name='assetrepairconsumeditem',
            name='item_code',
            field=models.CharField(max_length=100, verbose_name=' رمز العنصر'),
        ),
        migrations.AlterField(
            model_name='assetrepairconsumeditem',
            name='serial_no',
            field=models.CharField(max_length=100, verbose_name=' الرقم التسلسلي'),
        ),
        migrations.AlterField(
            model_name='assetrepairconsumeditem',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة الإجمالية '),
        ),
        migrations.AlterField(
            model_name='assetrepairconsumeditem',
            name='valuation_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name=' قيمة العنصر المستهلك'),
        ),
    ]
