# Generated by Django 4.2.6 on 2023-11-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_assetmaintenancelog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='maintenance_status',
            field=models.CharField(choices=[('Pending', 'قيد الانتظار'), ('In Progress', ' في تقدم'), ('Completed', 'جاهز'), ('Cancelled', 'ملغي')], default='Pending', max_length=20, verbose_name='حالةالصيانة'),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='repair_status',
            field=models.CharField(choices=[('Pending', 'قيد الانتظار'), ('In Progress', 'في تقدم '), ('Completed', 'جاهز'), ('Cancelled', 'ملغي')], default='Pending', max_length=20, verbose_name='حالة الإصلاح'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد الانتظار'), ('In Progress', ' في تقدم'), ('Completed', 'جاهز'), ('Cancelled', 'ملغي')], default='Pending', max_length=20, verbose_name='الحالة '),
        ),
    ]
