# Generated by Django 4.2.6 on 2023-11-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_department_options_alter_university_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='establishment_date',
            field=models.DateField(verbose_name='تاريخ التأسيس'),
        ),
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.CharField(choices=[('Especiall', 'خاصة'), ('governmental', 'حكوميه')], max_length=50, verbose_name='النوع'),
        ),
    ]
