# Generated by Django 4.2.6 on 2023-12-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_university_establishment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='establishment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التأسيس'),
        ),
    ]
