# Generated by Django 4.2.6 on 2023-12-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type_user',
        ),
    ]
