# Generated by Django 4.2.6 on 2023-12-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
